/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
package org.apache.streampipes.extensions.management.connect.adapter.parser;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.apache.streampipes.commons.exceptions.connect.ParseException;
import org.apache.streampipes.extensions.api.connect.IParser;
import org.apache.streampipes.extensions.api.connect.IParserEventHandler;
import org.apache.streampipes.model.connect.grounding.ParserDescription;
import org.apache.streampipes.model.connect.guess.GuessSchema;
import org.apache.streampipes.model.staticproperty.StaticProperty;
import org.apache.streampipes.sdk.builder.adapter.ParserDescriptionBuilder;
import org.apache.streampipes.sdk.extractor.StaticPropertyExtractor;
import org.apache.streampipes.sdk.helpers.Labels;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.protobuf.ByteString;
import com.google.protobuf.DescriptorProtos;
import com.google.protobuf.Descriptors;
import com.google.protobuf.Descriptors.DescriptorValidationException;
import com.google.protobuf.Descriptors.FieldDescriptor;
import com.google.protobuf.DynamicMessage;


public class ProtobufParser implements IParser {
  private static Logger logger = LoggerFactory.getLogger(ProtobufParser.class);
  public static final String ID = "org.apache.streampipes.extensions.management.connect.adapter.parser.protobuf";
  public static final String LABEL = "Protobuf";
  public static final String DESCRIPTION = "Can be used to read protobuf records";

  public static final String SCHEMA = "schema";
  public static final String MESSAGE_TYPE = "messageType";
  private final ParserUtils parserUtils;
  private Descriptors.Descriptor descriptor = null;

  public ProtobufParser() {
    logger.info("init protobuf parser");
    parserUtils = new ParserUtils();
  }

  public ProtobufParser(String schemaString, String messageType) throws IOException, DescriptorValidationException {
    this();
    // Step 1: Load the .desc file generated by protoc
    byte[] desc = Base64.getDecoder().decode(schemaString);
    DescriptorProtos.FileDescriptorSet descriptorSet = DescriptorProtos.FileDescriptorSet
        .parseFrom(new ByteArrayInputStream(desc));

    // Step 2: Build the FileDescriptor (assume one proto file)
    DescriptorProtos.FileDescriptorProto fileDescriptorProto = descriptorSet.getFile(0);
    Descriptors.FileDescriptor fileDescriptor = Descriptors.FileDescriptor.buildFrom(fileDescriptorProto,
        new Descriptors.FileDescriptor[] {});

    // Step 3: Get the message descriptor (replace with your actual message name)
    descriptor = fileDescriptor.findMessageTypeByName(messageType);

  }

  @Override
  public ParserDescription declareDescription() {
    return ParserDescriptionBuilder.create(ID, LABEL, DESCRIPTION)
        .requiredTextParameter(
            Labels.from(MESSAGE_TYPE, "Message Type", "protobuf message type of the incoming stream"), "SampleMessage")
        .requiredCodeblock(Labels.from(SCHEMA, "Schema", "The schema of the avro record"),
            "{\n" + " \"namespace\": \"example.avro\",\n" + " \"type\": \"record\",\n" + " \"name\": \"Test\",\n"
                + " \"fields\": [\n" + "     {\"name\": \"id\", \"type\": \"string\"},\n"
                + "     {\"name\": \"value\", \"type\": \"double\"}\n" + " ]\n" + "}")
        .build();
  }

  @Override
  public GuessSchema getGuessSchema(InputStream inputStream) throws ParseException {
    var event = getRecord(inputStream);
    return parserUtils.getGuessSchema(event);
  }

  @Override
  public void parse(InputStream inputStream, IParserEventHandler handler) throws ParseException {
    Map<String, Object> event = getRecord(inputStream);
    handler.handle(event);
  }

  @Override
  public IParser fromDescription(List<StaticProperty> configuration) {
    var extractor = StaticPropertyExtractor.from(configuration);
    String schema = extractor.codeblockValue(SCHEMA);
    String messageType = extractor.textParameter(MESSAGE_TYPE);
    logger.info("create protobuf parser from description {} {}", messageType, schema);
    try {
      return new ProtobufParser(schema, messageType);
    } catch (Exception e) {
      e.printStackTrace();
    }
    return null;
  }

  private Map<String, Object> getRecord(InputStream inputStream) throws ParseException {
    logger.info("ger record for input");
    try (InputStream base64DecodedStream = Base64.getDecoder().wrap(inputStream)) {
      DynamicMessage msg = DynamicMessage.parseFrom(descriptor, base64DecodedStream);
      return toMap(msg.getAllFields());
    } catch (IOException e) {
      e.printStackTrace();
      throw new ParseException("Error decoding the protobuf message. Please check the schema.");
    }
  }

  private Map<String, Object> toMap(Map<FieldDescriptor, Object> map) {
    Map<String, Object> resultMap = new LinkedHashMap<>();
    for (Map.Entry<FieldDescriptor, Object> field : map.entrySet()) {
        if (field.getKey().isMapField()) {
            resultMap.put(field.getKey().getJsonName(), toMap((Map<FieldDescriptor, Object>) field.getValue()));
        } else {
            Object value = convertProtobufValue(field.getValue());
            if( value != null) {
              if( field.getValue() != null) {
                logger.info("field: {} {} {}",field.getKey().getJsonName(), field.getValue(), field.getValue().getClass().toString());
              }
            }
            resultMap.put(field.getKey().getJsonName(), value);
        }
    }
    logger.info("to map result {}", resultMap);
    return resultMap;
  }

  private Object convertProtobufValue(Object value) {
    if (value == null) {
        return null;
    }

    if (value instanceof Descriptors.EnumValueDescriptor) {
        // Convert EnumValueDescriptor to its name
        return ((Descriptors.EnumValueDescriptor) value).getName();
    }else if ( value instanceof DynamicMessage) {
        return toMap(((DynamicMessage) value).getAllFields());
    }else if ( value instanceof ByteString) {
      int length = ((ByteString)value).size();
      ByteBuffer buffer = ((ByteString)value).asReadOnlyByteBuffer();
      buffer.order(ByteOrder.BIG_ENDIAN); // Or BIG_ENDIAN depending on C side
      short[] shorts = new short[length / 2];
      for (int i = 0; i < shorts.length; i++) {
          shorts[i] = buffer.getShort();
      }
      return shorts;
    } else if (value instanceof List) {
        // Handle repeated fields (lists)
        return ((List<?>) value).stream()
                .map(this::convertProtobufValue) // Recursively convert list items
                .toList();
    } else if (value instanceof Map) {
        // Handle nested maps
        return toMap((Map<FieldDescriptor, Object>) value);
    } else {
        // Return the value as-is for other types
        return value;
    }
  }

}
