/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
package org.apache.streampipes.extensions.management.connect.adapter.parser;

import org.apache.streampipes.commons.exceptions.connect.ParseException;
import org.apache.streampipes.extensions.api.connect.IParser;
import org.apache.streampipes.extensions.api.connect.IParserEventHandler;
import org.apache.streampipes.model.connect.grounding.ParserDescription;
import org.apache.streampipes.model.connect.guess.GuessSchema;
import org.apache.streampipes.model.staticproperty.StaticProperty;
import org.apache.streampipes.sdk.builder.adapter.ParserDescriptionBuilder;
import org.apache.streampipes.sdk.extractor.StaticPropertyExtractor;
import org.apache.streampipes.sdk.helpers.Labels;

import com.google.protobuf.DescriptorProtos;
import com.google.protobuf.Descriptors;
import com.google.protobuf.Descriptors.DescriptorValidationException;
import com.google.protobuf.Descriptors.FieldDescriptor;
import com.google.protobuf.DynamicMessage;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;


public class ProtobufParser implements IParser {
  public static final String ID = "org.apache.streampipes.extensions.management.connect.adapter.parser.protobuf";
  public static final String LABEL = "Protobuf";
  public static final String DESCRIPTION = "Can be used to read protobuf records";

  public static final String SCHEMA = "schema";
  public static final String MESSAGE_TYPE = "messageType";
  private final ParserUtils parserUtils;
  private Descriptors.Descriptor descriptor = null;

  public ProtobufParser() {
    parserUtils = new ParserUtils();
  }

  public ProtobufParser(String schemaString, String messageType) throws IOException, DescriptorValidationException {
    this();
    // Step 1: Load the .desc file generated by protoc
    byte[] desc = Base64.getDecoder().decode(schemaString);
    DescriptorProtos.FileDescriptorSet descriptorSet = DescriptorProtos.FileDescriptorSet
        .parseFrom(new ByteArrayInputStream(desc));

    // Step 2: Build the FileDescriptor (assume one proto file)
    DescriptorProtos.FileDescriptorProto fileDescriptorProto = descriptorSet.getFile(0);
    Descriptors.FileDescriptor fileDescriptor = Descriptors.FileDescriptor.buildFrom(fileDescriptorProto,
        new Descriptors.FileDescriptor[] {});

    // Step 3: Get the message descriptor (replace with your actual message name)
    descriptor = fileDescriptor.findMessageTypeByName(messageType);

  }

  @Override
  public ParserDescription declareDescription() {
    return ParserDescriptionBuilder.create(ID, LABEL, DESCRIPTION)
        .requiredTextParameter(
            Labels.from(MESSAGE_TYPE, "Message Type", "protobuf message type of the incoming stream"), "SampleMessage")
        .requiredCodeblock(Labels.from(SCHEMA, "Schema", "The schema of the avro record"),
            "{\n" + " \"namespace\": \"example.avro\",\n" + " \"type\": \"record\",\n" + " \"name\": \"Test\",\n"
                + " \"fields\": [\n" + "     {\"name\": \"id\", \"type\": \"string\"},\n"
                + "     {\"name\": \"value\", \"type\": \"double\"}\n" + " ]\n" + "}")
        .build();
  }

  @Override
  public GuessSchema getGuessSchema(InputStream inputStream) throws ParseException {
    var event = getRecord(inputStream);
    return parserUtils.getGuessSchema(event);
  }

  @Override
  public void parse(InputStream inputStream, IParserEventHandler handler) throws ParseException {
    Map<String, Object> event = getRecord(inputStream);
    handler.handle(event);
  }

  @Override
  public IParser fromDescription(List<StaticProperty> configuration) {
    var extractor = StaticPropertyExtractor.from(configuration);
    String schema = extractor.codeblockValue(SCHEMA);
    String mesasgeType = extractor.textParameter(MESSAGE_TYPE);
    try {
      return new ProtobufParser(schema, mesasgeType);
    } catch (Exception e) {
      e.printStackTrace();
    }
    return null;
  }

  private Map<String, Object> getRecord(InputStream inputStream) throws ParseException {
    try (InputStream base64DecodedStream = Base64.getDecoder().wrap(inputStream)) {
      DynamicMessage msg = DynamicMessage.parseFrom(descriptor, base64DecodedStream);
      return toMap(msg.getAllFields());
    } catch (IOException e) {
      e.printStackTrace();
      throw new ParseException("Error decoding the protobuf message. Please check the schema.");
    }
  }

  private Map<String, Object> toMap(Map<FieldDescriptor, Object> map) {
    Map<String, Object> resultMap = new LinkedHashMap<>();
    for (Map.Entry<FieldDescriptor, Object> field : map.entrySet()) {
      if (field.getKey().isMapField()) {
        resultMap.put(field.getKey().getJsonName(), toMap((Map<FieldDescriptor, Object>) field.getValue()));
      } else {
        resultMap.put(field.getKey().getJsonName(), field.getValue());
      }
    }

    return resultMap;
  }

}
